version: '3.8'
services:
  comment-service:
    build: .
    container_name: comment-service
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/comment-service
      - SPRING_DATASOURCE_USERNAME=test
      - SPRING_DATASOURCE_PASSWORD=test
  db:
    image: postgres:13.7-alpine
    container_name: postgres
    ports:
      - "6541:5432"
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
      POSTGRES_DB: comment-service